
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  socket: /var/run/mysqld/mysqld.sock
#  host: 104.199.252.193 # #35.185.128.127
  host: 35.185.128.127
  port: 3306

development:
  <<: *default
  database: fc16

test:
  <<: *default
  database: fc16

production:
  <<: *default
  database: fc16
    
